version: '3.2'

services:
  db:
    image: postgres:10.5
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=best
      - POSTGRES_PASSWORD=best
      - POSTGRES_DB=best
    ports:
      - 5432:5432

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 30000:8080

  nginx:
    image: nginx
    ports:
      - 30001:80
    volumes:
      - ./application:/var/www/html/code
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d/:/etc/nginx/conf.d/
      - ./nginx/log:/var/log/nginx

  symfony-web:
    build: .
    volumes:
      - ./application:/var/www/html/code
      - ./symfony/php-fpm_conf/etc:/usr/local/etc
    ports:
      - 9000:9000
    
volumes:
  db-data: